### PR TITLE
Patched remove_old_images

### LINKED ISSUE #1782: media regenerate fails for files without metadata
When there is a file without valid metadata, for whatever reason, remove_old_images should fail safely without throwing PHP warnings.

### PR DESCRIPTION
**Pull request by michalkleiner**
Safely fail for files without metadata

Fixes https://github.com/wp-cli/wp-cli/issues/1782

### CODE REVIEW

File: php/commands/media.php [hunk 1]
```diff
@@ -233,14 +233,14 @@ private function remove_old_images( $att_id ) {
...
 		$metadata = wp_get_attachment_metadata( $att_id );
+		
+		if ( !is_array($metadata) || !array_key_exists('sizes', $metadata) || empty($metadata['sizes'])) {
+			return;
+		}
 
 		$dir_path = $wud['basedir'] . '/' . dirname( $metadata['file'] ) . '/';
 		$original_path = $dir_path . basename( $metadata['file'] );
 
-		if ( empty( $metadata['sizes'] ) ) {
```
Comment (danielbachhuber) [inline php/commands/media.php:240]: Can you keep this check please?

Comment (michalkleiner) [inline php/commands/media.php:240]: The check is still there, it just goes above creating of the paths as they are not needed when it fails.
